name: 'PHP Analyzer'
description: 'A custom PHP static analyzer without Composer'
author: 'ClousCloud'
inputs:
  directory:
    description: 'The directory containing PHP files to analyze'
    required: true
    default: './src'
runs:
  using: 'docker'
  image: 'php:8.1-cli'
  entrypoint: 'php'
  args:
    - /github/workspace/analyzer.php
    - ${{ inputs.directory }}
