# action.yml
name: 'SPHPS Analyzer'
description: 'A custom PHP static analyzer without Composer, with extended features'
author: 'ClousCloud'
inputs:
  directory:
    description: 'The directory containing PHP files to analyze'
    required: true
    default: './src'
runs:
  using: 'docker'
  image: 'docker://php:8.1-cli'
  entrypoint: 'php'
  args:
    - analyzer.php
    - ${{ inputs.directory }}

branding:
  icon: 'code'
  color: 'blue'
